In [7]:
import numpy as np

In [21]:
sample_list=[4, 5, 6, "a"]
sample_list

[4, 5, 6, 'a']

In [23]:
#Creating array
list_of_list=[[5, 6, 7], [8, 9, 10], [11, 12, 13]]
np.array(list_of_list)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [22]:
arr=np.array([4, 5, 6])
array

array([4, 5, 6])

In [9]:
#range of numbers -note python indexing starts from zero and last number will be excluded
np.arange(5, 20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(5, 20, 5)

array([ 5, 10, 15])

In [12]:
np.arange(5, 20, 5, dtype=float)

array([ 5., 10., 15.])

In [102]:
np.zeros(10, dtype='float')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.linspace(0, 20, 19)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ,
       11.11111111, 12.22222222, 13.33333333, 14.44444444, 15.55555556,
       16.66666667, 17.77777778, 18.88888889, 20.        ])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.randn(2, 3)

array([[ 1.02870156, -2.29745333, -0.12386542],
       [ 0.91847484,  0.40192727,  0.002315  ]])

In [20]:
np.random.randint(1, 10)

4

In [25]:
a=np.random.rand(5,4)
a

array([[0.35727272, 0.54322186, 0.3707489 , 0.37127036],
       [0.979361  , 0.94385505, 0.88941729, 0.79789277],
       [0.4411643 , 0.05066222, 0.59157139, 0.18582659],
       [0.94996511, 0.32285823, 0.41338135, 0.70233701],
       [0.88416171, 0.63800701, 0.9553056 , 0.1038902 ]])

In [26]:
a.reshape(2, 10)

array([[0.35727272, 0.54322186, 0.3707489 , 0.37127036, 0.979361  ,
        0.94385505, 0.88941729, 0.79789277, 0.4411643 , 0.05066222],
       [0.59157139, 0.18582659, 0.94996511, 0.32285823, 0.41338135,
        0.70233701, 0.88416171, 0.63800701, 0.9553056 , 0.1038902 ]])

In [32]:
b=np.random.randint(0, 50, 100)
c=b.reshape(10, 10)
c

array([[36, 48, 45,  5, 47, 43, 43, 27, 25, 28],
       [10, 13, 41, 14,  3, 23, 46,  1, 34,  9],
       [39, 29, 11, 23, 15, 18, 14, 39, 20,  3],
       [49,  1, 30, 20, 40, 25, 13, 39, 17, 24],
       [38, 14,  3, 41, 40, 49,  7, 13,  1, 23],
       [28, 33, 28, 17, 22, 48, 36, 16, 10, 22],
       [12, 14,  8, 40, 11, 41, 29, 31, 12, 34],
       [13,  2, 16, 13, 15, 15, 37, 18, 45, 32],
       [45, 31, 29, 35, 30, 37, 39, 32,  1, 24],
       [21, 48, 46, 13, 30, 40, 40, 47, 45, 14]])

In [33]:
c.T

array([[36, 10, 39, 49, 38, 28, 12, 13, 45, 21],
       [48, 13, 29,  1, 14, 33, 14,  2, 31, 48],
       [45, 41, 11, 30,  3, 28,  8, 16, 29, 46],
       [ 5, 14, 23, 20, 41, 17, 40, 13, 35, 13],
       [47,  3, 15, 40, 40, 22, 11, 15, 30, 30],
       [43, 23, 18, 25, 49, 48, 41, 15, 37, 40],
       [43, 46, 14, 13,  7, 36, 29, 37, 39, 40],
       [27,  1, 39, 39, 13, 16, 31, 18, 32, 47],
       [25, 34, 20, 17,  1, 10, 12, 45,  1, 45],
       [28,  9,  3, 24, 23, 22, 34, 32, 24, 14]])

In [36]:
c.max(), c.min(), c.argmin(), c.argmax()

(49, 1, 17, 30)

In [64]:
a=np.random.randn(5, 20)
a.shape
a.reshape(10, 10)

array([[-1.34569073,  0.65611556, -0.22752596,  0.79758566,  1.11407801,
        -0.77080343, -1.00936318,  0.64215012,  0.64392436, -0.19780332],
       [ 0.04351712, -0.4357547 ,  0.72330274,  0.53476641, -1.00141904,
         0.78842321,  0.46671782, -0.53222216,  0.51729024, -0.06942257],
       [ 0.38733527,  0.3304401 ,  1.65369832, -0.19077238,  0.18978368,
         0.36307696, -0.51489974, -0.48265586, -1.43708424,  1.36424491],
       [ 2.63408536,  0.7939056 , -0.52238313, -0.17423163, -0.23432486,
        -2.14419598, -0.41835759,  0.5530439 , -1.04026713,  0.42669875],
       [ 1.63773443,  2.42916741, -0.62031261, -0.29787693, -0.49904653,
        -0.42010873,  1.19236517, -0.0469156 , -1.66104902,  0.80578648],
       [ 0.14165007,  1.40842715, -2.37103845, -0.45704641,  1.9221909 ,
        -0.06446817, -0.17377881,  0.2477305 ,  0.4860821 ,  0.9221969 ],
       [-0.6538066 , -0.27246711,  1.17451449, -0.51870717, -0.24219542,
        -0.76677209,  0.75317973,  0.17910558

In [66]:
B=np.random.rand(5, 20)
B

array([[0.3740611 , 0.17346358, 0.1386613 , 0.87001481, 0.84725536,
        0.81321991, 0.49217337, 0.30969248, 0.97870045, 0.60951537,
        0.73416699, 0.89706391, 0.19402563, 0.48088274, 0.03659829,
        0.89936234, 0.96254466, 0.60234609, 0.1979255 , 0.94118442],
       [0.01918924, 0.76099013, 0.19515974, 0.50184372, 0.19982291,
        0.10376631, 0.13756595, 0.17643995, 0.28310284, 0.8056289 ,
        0.15066653, 0.51189005, 0.54922443, 0.51068256, 0.80231603,
        0.07342351, 0.54565198, 0.35008956, 0.8053589 , 0.72834251],
       [0.04653612, 0.35196355, 0.32334741, 0.56560519, 0.4290856 ,
        0.76802636, 0.63545381, 0.62657065, 0.20744493, 0.28025914,
        0.26588238, 0.51278598, 0.95645356, 0.13727827, 0.91426457,
        0.28139675, 0.67127627, 0.9549615 , 0.06181765, 0.78501976],
       [0.57639453, 0.06507006, 0.68144906, 0.83344925, 0.22917661,
        0.63707991, 0.88439385, 0.34352702, 0.14728571, 0.08352782,
        0.52884954, 0.72754736, 0.35441985, 0

In [70]:
C=np.random.randint(5, 20, 100)
C.reshape(10, 10)

array([[ 6, 14, 19,  6, 11, 11, 16, 11, 11, 18],
       [14, 18, 18, 14,  6, 17,  6, 15,  8, 11],
       [ 7,  6, 16, 11, 13, 13, 19,  5, 11,  9],
       [13, 16,  6, 15, 13, 14,  9, 18,  7, 14],
       [10, 13, 17,  6, 13,  6,  5, 19,  6, 16],
       [17, 14,  8,  7,  8, 16,  8,  7, 18, 11],
       [17, 10, 15, 16, 12,  5, 16,  7, 12, 15],
       [14, 19, 13, 13,  5, 15, 14, 12, 14, 10],
       [ 9,  8, 18, 12, 13,  8, 10,  6,  6, 17],
       [12, 15, 18, 17, 14,  9, 11,  6, 15,  9]])

In [74]:
D=np.random.randint(5, size=(10, 10))
D

array([[3, 0, 3, 2, 4, 4, 2, 4, 2, 2],
       [3, 3, 1, 2, 0, 0, 4, 1, 2, 0],
       [1, 2, 0, 1, 4, 3, 2, 2, 0, 0],
       [2, 2, 3, 1, 1, 2, 3, 0, 2, 1],
       [3, 2, 3, 3, 3, 2, 2, 3, 1, 4],
       [0, 0, 0, 3, 0, 2, 1, 1, 0, 1],
       [2, 2, 2, 1, 1, 3, 1, 1, 2, 1],
       [0, 3, 0, 1, 1, 1, 3, 2, 3, 3],
       [3, 4, 2, 2, 2, 0, 3, 4, 1, 2],
       [2, 1, 4, 0, 3, 0, 3, 3, 2, 1]])

In [75]:
matrix=np.array(([1, 2, 3, 4], [5, 6, 7, 8], [9,10, 11, 12]))
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
matrix[0][3]

4

In [77]:
matrix[:, 0]

array([1, 5, 9])

In [79]:
matrix[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [84]:
array=np.arange(5, 11)
array

array([ 5,  6,  7,  8,  9, 10])

In [86]:
bool=array<8
bool

array([ True,  True,  True, False, False, False])

In [87]:
np.sqrt(array)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [88]:
np.log(array)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [89]:
np.exp(array)

array([  148.4131591 ,   403.42879349,  1096.63315843,  2980.95798704,
        8103.08392758, 22026.46579481])

In [94]:
array1=np.arange(5, 11)
array2=np.arange(12, 18)
a=array1.reshape(2, 3), b=array2.reshape(3, 2)

(array([[ 5,  6,  7],
        [ 8,  9, 10]]),
 array([[12, 13],
        [14, 15],
        [16, 17]]))

In [100]:
np.std(a), np.var(a), 

(1.0204014340543015, 1.041219086620075)

In [101]:
sports=np.array(['golf', 'cric', 'fball', 'fball', 'cric'])
np.unique(sports)

array(['cric', 'fball', 'golf'], dtype='<U5')